spring.application.name=Categorias

server.port=9002

# Credenciales y ruta de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/categorias?createDatabaseIfNotExist=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=
spring.datasource.password=

# JPA config
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
